package property

const (
	Key                     = "Key"
	Id                      = "Id"
	RouterHash              = "RouterHash"
	DomainId                = "DomainId"
	RouterIp                = "RouterIp"
	PeerHash                = "PeerHash"
	PeerIp                  = "PeerIp"
	PeerAsn                 = "PeerASN"
	Timestamp               = "Timestamp"
	IgpRouterId             = "IgpRouterId"
	Asn                     = "Asn"
	Mtid                    = "Mtid"
	AreaId                  = "AreaId"
	Protocol                = "Protocol"
	ProtocolId              = "ProtocolId"
	Name                    = "Name"
	IsPrepolicy             = "IsPrepolicy"
	IsAdjRibIn              = "IsAdjRibIn"
	Nexthop                 = "Nexthop"
	LocalLinkIp             = "LocalLinkIp"
	RemoteLinkIp            = "RemoteLinkIp"
	IgpMetric               = "IgpMetric"
	RemoteNodeHash          = "RemoteNodeHash"
	LocalNodeHash           = "LocalNodeHash"
	RemoteIgpRouterId       = "RemoteIgpRouterId"
	Prefix                  = "Prefix"
	PrefixLen               = "PrefixLen"
	PrefixMetric            = "PrefixMetric"
	LocalNodeAsn            = "LocalNodeAsn"
	IgpFlags                = "IgpFlags"
	Srv6Sid                 = "Srv6Sid"
	DataRate                = "DataRate"
	PacketsSent             = "PacketsSent"
	PacketsReceived         = "PacketsReceived"
	State                   = "State"
	LastStateTransitionTime = "LastStateTransitionTime"
	From                    = "From"
	To                      = "To"
	Link                    = "Link"
	LsNodeKey               = "LsNodeKey"
	Latitude                = "Latitude"
	Longitude               = "Longitude"
	UnidirLinkDelay         = "UnidirLinkDelay"
	UnidirLinkDelayMinMax   = "UnidirLinkDelayMinMax"
)
